### PR TITLE
fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failures raised since version 2.8 and https://github.com/troglobit/inadyn/commit/1928d7a80390a2ef651a32d5723531fca51384d4:

```
ddns.c: In function 'is_address_valid':
ddns.c:193:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (size_t i = 0; i < NELEMS(except); i++) {
  ^
```

Fixes:
 - http://autobuild.buildroot.org/results/9323cc7afceff75f7d41ff161b8d0ec9aefa164a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by troglobit** [comment]
Awesome, thanks!

**Comment by troglobit** [comment]
@ffontaine I'm planning a .1 release in the next couple of days, so I can tend to this making it into Buildroot if you like. I know you have a lot else on your plate.

**Comment by ffontaine** [comment]
Sure, I'll let you handle the bump on buildroot side.
